name: detect-unused-secrets

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Detect unused secrets
        uses: nearform-actions/github-action-detect-unused-secrets@v1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}